### PR TITLE
Improve AssemblyScript

### PR DESCRIPTION
**Pull request by MaxGraey**

### CODE REVIEW

**Comment by MaxGraey** [comment]
It could be improve much more if remove `Color` class at all  and work with raw color data btw. It will eliminate unnecessary alloc memory and reference counting

**Comment by alexvictoor** [comment]
Woah! Thanks a lot, I will take some time to understand your improvements. Do you think that even with the flyweight pattern the Color class kills performances?

**Comment by MaxGraey** [comment]
every time when you do `new Color` it alloc memory, increase counter, decrease counter, do some checks. In future with multi-value proposal for such simple classes / struct will be use "scalar replacment" but for current moment I suggest avoid using allocations inside high loaded loops. Also see this [issue](https://github.com/AssemblyScript/assemblyscript/issues/997)

**Comment by alexvictoor** [comment]
Thanks again a lot!
I was not expecting such perf improvements!
Do you have some pointers on what does unchecked() exactly?

**Comment by MaxGraey** [comment]
`unchecked` is just skip bound checks which usually drastically increase perf. In future we will eliminate this checks during opt phase (it's called [bounds checking elimination](https://en.wikipedia.org/wiki/Bounds-checking_elimination)) but now you should optimize it manually if you care about performance

**Pull request merged**
